application: ascii-chan 
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /templates/css
  static_dir: css

- url: /.*
  script: asciichan.app


libraries:
- name: jinja2
  version: latest
